config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  get 'home/about'

  get 'home/index'
  root 'home#index'

  resources :pages

end

app/models/page.rb
class Page < ActiveRecord::Base
    has_paper_trail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pages = Page.last(3).reverse
  end

  def about
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.all
  end

  def show
  end

  def edit
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      flash[:success] = "Page created!"
      redirect_to @page
    end
  end

  def update
    if @page.update(page_params)
      flash[:success] = "Page updated!"
      redirect_to @page
    end
  end

  private

    def set_page
      @page = Page.find(params[:id])
    end

    def page_params
      params.require(:page).permit(:title, :content)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/home/about.html.erb
<h1>About</h1>
<p>Information about site goes here.</p>

app/views/home/index.html.erb
<div class="row">
    <div class="landing head col-sm-12 col-lg-12">
        <p>
        Tunnel Wiki
        </p>
    </div>
    <div class="landing search col-sm-8 col-lg-6">
        <form class="form">
            <input type="text" class="form-control" placeholder="Search...">
        </form>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Tunnel Wiki</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <nav class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Tunnel Wiki</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav"> 
                    <li class=<%= 'active' if controller.action_name == 'index'%>>
                    <%= link_to "Home", root_url %> 
                    </li>

                    <li class=<%= 'active' if controller.action_name == 'about'%>>
                    <%= link_to "About", {:controller => :home, :action => :about} %>
                    </li>
                </ul>
                <form class="navbar-form navbar-right">
                    <input type="text" class="form-control" placeholder="Search...">
                </form>
            </div><!--/.nav-collapse -->
        </div>
        </nav>

        <div class="container">
            <%= yield %>
        </div>

        <hr />

        <div class="container">
            <footer>
            <p>&copy; copyright information (creative commons?)</p>
            </footer>
        </div>

    </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Tunnel Wiki</title>
        <%= stylesheet_link_tag    'home' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>

        <div class="container">
            <%= yield %>
        </div>

        <%# <hr /> %>

        <%# <div class="container"> %>
        <%#     <footer> %>
        <%#     <p>&copy; copyright information (creative commons?)</p> %>
        <%#     </footer> %>
        <%# </div> %>

    </body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f|%>
    <div class="field form-group">
        <%= f.label :title %><br />
        <%= f.text_field :title , :class => "form-control"%>
    </div>

    <div class="field form-group">
        <%= f.label :content %><br />
        <%= f.text_area :content , :class => "form-control"%>
    </div>

    <div class="actions">
        <%= f.submit 'Submit', :class => "btn btn-primary" %>
    </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Edit page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_index_path %>

app/views/pages/index.html.erb
<h1>All Pages</h1>

<ul>
    <% @pages.each do |p| %>
        <li><%= p.title %> <%= link_to 'show', p %></li>
    <% end %>
</ul>

<%= link_to "New Page", new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_index_path %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>

<p>
<%= @page.content%>
</p>


<%= link_to "edit", edit_page_path(@page) %>
<%= link_to "back", pages_index_path %>

<div>
<table class="table table-bordered table-striped">
    <tr>
        <th>#</th>
        <th>Action</th>
        <th>Version</th>
        <th>Time</th>
        <th>User</th>
    </tr>
        <% @page.versions.each do |v| %>
            <tr>
                <td><%= v.index%> </td>
                <td><%= v.event %> </td>
                <td><%= v.reify %> </td>
                <td><%= v.created_at %></td>
                <td><%= v.whodunnit%></td>
            </tr>
        <% end %>
</table>
    
</div>